In [1]:
import pandas as pd
import matplotlib.pyplot as plt

data_df = pd.read_csv('datasets/국내지진목록.csv')

In [2]:
data_df

,"국내 지진 검색 결과를 번호, 발생시각, 규모, 깊이, 위도, 경도, 위치, 지도보기로 제공하는 표",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,번호,발생시각,규모,깊이(km),최대\n진도,위도,경도,위치,지도보기,상세정보\n(진도 등)
1,101,2023/09/22 17:46:58,2.2,14,Ⅱ,36.59 N,128.22 E,경북 문경시 동쪽 3km 지역,지도,상세정보
2,100,2023/09/16 04:28:25,2.2,7,Ⅱ,36.01 N,128.01 E,경북 김천시 남남서쪽 17km 지역,지도,상세정보
3,99,2023/09/14 21:28:25,2.9,23,Ⅰ,35.70 N,130.03 E,울산 동구 동북동쪽 60km 해역,지도,상세정보
4,98,2023/09/08 05:12:01,2.3,19,Ⅰ,41.32 N,129.17 E,북한 함경북도 길주 북북서쪽 43km 지역,지도,상세정보
...,...,...,...,...,...,...,...,...,...,...
97,5,2022/09/22 20:28:37,2.9,10,Ⅰ,40.57 N,126.71 E,북한 자강도 용림 북북동쪽 7km 지역,지도,상세정보
98,4,2022/09/11 16:28:35,2.4,13,Ⅰ,36.46 N,129.63 E,경북 영덕군 동북동쪽 24km 해역,지도,상세정보
99,3,2022/09/10 14:59:48,3.4,7,Ⅱ,38.95 N,127.29 E,북한 강원 원산 남남서쪽 26km 지역,지도,상세정보
100,2,2022/09/03 00:44:46,2.0,18,Ⅰ,36.39 N,129.89 E,경북 영덕군 동쪽 47km 해역,지도,상세정보
101,1,2022/09/01 08:33:53,2.5,-,Ⅰ,35.11 N,125.07 E,전남 신안군 흑산도 북북서쪽 58km 해역,지도,상세정보

In [3]:
data_df.shape

(102, 10)

In [4]:
data_df.columns = ["번호", "발생시각", "규모",	"깊이(km)",	"진도", "위도", "경도", "위치", "지도보기", "상세정보"]

In [5]:
data_df

,번호,발생시각,규모,깊이(km),진도,위도,경도,위치,지도보기,상세정보
0,번호,발생시각,규모,깊이(km),최대\n진도,위도,경도,위치,지도보기,상세정보\n(진도 등)
1,101,2023/09/22 17:46:58,2.2,14,Ⅱ,36.59 N,128.22 E,경북 문경시 동쪽 3km 지역,지도,상세정보
2,100,2023/09/16 04:28:25,2.2,7,Ⅱ,36.01 N,128.01 E,경북 김천시 남남서쪽 17km 지역,지도,상세정보
3,99,2023/09/14 21:28:25,2.9,23,Ⅰ,35.70 N,130.03 E,울산 동구 동북동쪽 60km 해역,지도,상세정보
4,98,2023/09/08 05:12:01,2.3,19,Ⅰ,41.32 N,129.17 E,북한 함경북도 길주 북북서쪽 43km 지역,지도,상세정보
...,...,...,...,...,...,...,...,...,...,...
97,5,2022/09/22 20:28:37,2.9,10,Ⅰ,40.57 N,126.71 E,북한 자강도 용림 북북동쪽 7km 지역,지도,상세정보
98,4,2022/09/11 16:28:35,2.4,13,Ⅰ,36.46 N,129.63 E,경북 영덕군 동북동쪽 24km 해역,지도,상세정보
99,3,2022/09/10 14:59:48,3.4,7,Ⅱ,38.95 N,127.29 E,북한 강원 원산 남남서쪽 26km 지역,지도,상세정보
100,2,2022/09/03 00:44:46,2.0,18,Ⅰ,36.39 N,129.89 E,경북 영덕군 동쪽 47km 해역,지도,상세정보
101,1,2022/09/01 08:33:53,2.5,-,Ⅰ,35.11 N,125.07 E,전남 신안군 흑산도 북북서쪽 58km 해역,지도,상세정보

In [6]:
data_df = data_df.drop([0])

In [7]:
data_df.drop("번호", axis = 1, inplace=True)

In [8]:
data_df.drop('지도보기', axis = 1, inplace=True)

In [9]:
data_df.drop('상세정보', axis = 1, inplace=True)

In [72]:
data_df

,발생시각,규모,깊이(km),진도,위도,경도,위치
1,2023/09/22 17:46:58,2.2,14,Ⅱ,36.59 N,128.22 E,경북 문경시 동쪽 3km 지역
2,2023/09/16 04:28:25,2.2,7,Ⅱ,36.01 N,128.01 E,경북 김천시 남남서쪽 17km 지역
3,2023/09/14 21:28:25,2.9,23,Ⅰ,35.70 N,130.03 E,울산 동구 동북동쪽 60km 해역
4,2023/09/08 05:12:01,2.3,19,Ⅰ,41.32 N,129.17 E,북한 함경북도 길주 북북서쪽 43km 지역
5,2023/09/08 04:01:16,2.1,24,Ⅰ,41.30 N,129.23 E,북한 함경북도 길주 북북서쪽 39km 지역
...,...,...,...,...,...,...,...
97,2022/09/22 20:28:37,2.9,10,Ⅰ,40.57 N,126.71 E,북한 자강도 용림 북북동쪽 7km 지역
98,2022/09/11 16:28:35,2.4,13,Ⅰ,36.46 N,129.63 E,경북 영덕군 동북동쪽 24km 해역
99,2022/09/10 14:59:48,3.4,7,Ⅱ,38.95 N,127.29 E,북한 강원 원산 남남서쪽 26km 지역
100,2022/09/03 00:44:46,2.0,18,Ⅰ,36.39 N,129.89 E,경북 영덕군 동쪽 47km 해역
101,2022/09/01 08:33:53,2.5,-,Ⅰ,35.11 N,125.07 E,전남 신안군 흑산도 북북서쪽 58km 해역

In [73]:
data_df = data_df.rename(columns = {'발생시각' : 'OT',  '규모' : 'MT', '깊이(km)' : 'DEP', '진도' : 'SC', '위도' : 'LAT', '경도' : 'LON', '위치' : 'SPOT'})

In [74]:
data_df

,OT,MT,DEP,SC,LAT,LON,SPOT
1,2023/09/22 17:46:58,2.2,14,Ⅱ,36.59 N,128.22 E,경북 문경시 동쪽 3km 지역
2,2023/09/16 04:28:25,2.2,7,Ⅱ,36.01 N,128.01 E,경북 김천시 남남서쪽 17km 지역
3,2023/09/14 21:28:25,2.9,23,Ⅰ,35.70 N,130.03 E,울산 동구 동북동쪽 60km 해역
4,2023/09/08 05:12:01,2.3,19,Ⅰ,41.32 N,129.17 E,북한 함경북도 길주 북북서쪽 43km 지역
5,2023/09/08 04:01:16,2.1,24,Ⅰ,41.30 N,129.23 E,북한 함경북도 길주 북북서쪽 39km 지역
...,...,...,...,...,...,...,...
97,2022/09/22 20:28:37,2.9,10,Ⅰ,40.57 N,126.71 E,북한 자강도 용림 북북동쪽 7km 지역
98,2022/09/11 16:28:35,2.4,13,Ⅰ,36.46 N,129.63 E,경북 영덕군 동북동쪽 24km 해역
99,2022/09/10 14:59:48,3.4,7,Ⅱ,38.95 N,127.29 E,북한 강원 원산 남남서쪽 26km 지역
100,2022/09/03 00:44:46,2.0,18,Ⅰ,36.39 N,129.89 E,경북 영덕군 동쪽 47km 해역
101,2022/09/01 08:33:53,2.5,-,Ⅰ,35.11 N,125.07 E,전남 신안군 흑산도 북북서쪽 58km 해역

In [75]:
def clean_location(data_df):
    # "°"와 "N"을 빈 문자열로 대체하여 제거
    cleaned_location = data_df.replace(" N", "")
    return cleaned_location
# 'Location' 컬럼에 apply() 함수 적용
data_df['LAT'] = data_df['LAT'].apply(clean_location)

In [76]:
def clean_location(data_df):
    # "°"와 "N"을 빈 문자열로 대체하여 제거
    cleaned_location = data_df.replace(" E", "")
    return cleaned_location
# 'Location' 컬럼에 apply() 함수 적용
data_df['LON'] = data_df['LON'].apply(clean_location)

In [77]:
data_df

                      OT   MT DEP SC    LAT     LON                     SPOT
1    2023/09/22 17:46:58  2.2  14  Ⅱ  36.59  128.22         경북 문경시 동쪽 3km 지역
2    2023/09/16 04:28:25  2.2   7  Ⅱ  36.01  128.01      경북 김천시 남남서쪽 17km 지역
3    2023/09/14 21:28:25  2.9  23  Ⅰ  35.70  130.03       울산 동구 동북동쪽 60km 해역
4    2023/09/08 05:12:01  2.3  19  Ⅰ  41.32  129.17  북한 함경북도 길주 북북서쪽 43km 지역
5    2023/09/08 04:01:16  2.1  24  Ⅰ  41.30  129.23  북한 함경북도 길주 북북서쪽 39km 지역
..                   ...  ...  .. ..    ...     ...                      ...
97   2022/09/22 20:28:37  2.9  10  Ⅰ  40.57  126.71    북한 자강도 용림 북북동쪽 7km 지역
98   2022/09/11 16:28:35  2.4  13  Ⅰ  36.46  129.63      경북 영덕군 동북동쪽 24km 해역
99   2022/09/10 14:59:48  3.4   7  Ⅱ  38.95  127.29    북한 강원 원산 남남서쪽 26km 지역
100  2022/09/03 00:44:46  2.0  18  Ⅰ  36.39  129.89        경북 영덕군 동쪽 47km 해역
101  2022/09/01 08:33:53  2.5   -  Ⅰ  35.11  125.07  전남 신안군 흑산도 북북서쪽 58km 해역

[101 rows x 7 columns]

In [79]:
excel_file_path = 'korea_2.xlsx'
data_df.to_excel(excel_file_path, index=False)

In [11]:
data1 = pd.read_csv('C:\Pandas\project(mini1)\datasets\地震リスト (1).csv')
data1

         地震の発生日     地震の発生時刻     震央地名         緯度          経度     深さ    Ｍ 最大震度
0    2023/05/20  23:11:21.2   千葉県南東沖  34°57.6′N  140°13.1′E  79 km  4.2  震度２
1    2023/05/20  12:21:40.2  トカラ列島近海  29°55.8′N  130°02.6′E  11 km  2.3  震度１
2    2023/05/20  11:27:55.8  トカラ列島近海  29°55.8′N  130°01.1′E   9 km  2.2  震度１
3    2023/05/20  04:13:49.5      三陸沖  39°37.6′N  144°28.4′E  54 km  4.7  震度１
4    2023/05/20  00:57:58.0   与那国島近海  24°21.6′N  122°59.1′E  48 km  3.2  震度１
..          ...         ...      ...        ...         ...    ...  ...  ...
995  2022/11/09  09:18:47.7     宮城県沖  38°27.3′N  141°53.3′E  55 km  4.0  震度１
996  2022/11/09  05:28:59.1   奄美大島近海  27°58.6′N  129°09.4′E  17 km  3.2  震度１
997  2022/11/09  02:38:10.6    宮古島近海  24°49.2′N  125°22.7′E  49 km  3.9  震度２
998  2022/11/08  17:38:53.7  石川県能登地方  37°30.1′N  137°12.6′E  13 km  3.0  震度１
999  2022/11/08  14:14:00.9  トカラ列島近海  29°37.6′N  129°45.7′E   8 km  3.6  震度３

[1000 rows x 8 columns]

In [12]:
# 컬럼명 변경 
data1.columns = ['발생일', '발생시각', '위치', '위도', '경도', '깊이(km)', '규모', '진도']
data1
# 컬럼 삭제
# 컬럼 순서 바꾸고

            발생일        발생시각       위치         위도          경도 깊이(km)   규모   진도
0    2023/05/20  23:11:21.2   千葉県南東沖  34°57.6′N  140°13.1′E  79 km  4.2  震度２
1    2023/05/20  12:21:40.2  トカラ列島近海  29°55.8′N  130°02.6′E  11 km  2.3  震度１
2    2023/05/20  11:27:55.8  トカラ列島近海  29°55.8′N  130°01.1′E   9 km  2.2  震度１
3    2023/05/20  04:13:49.5      三陸沖  39°37.6′N  144°28.4′E  54 km  4.7  震度１
4    2023/05/20  00:57:58.0   与那国島近海  24°21.6′N  122°59.1′E  48 km  3.2  震度１
..          ...         ...      ...        ...         ...    ...  ...  ...
995  2022/11/09  09:18:47.7     宮城県沖  38°27.3′N  141°53.3′E  55 km  4.0  震度１
996  2022/11/09  05:28:59.1   奄美大島近海  27°58.6′N  129°09.4′E  17 km  3.2  震度１
997  2022/11/09  02:38:10.6    宮古島近海  24°49.2′N  125°22.7′E  49 km  3.9  震度２
998  2022/11/08  17:38:53.7  石川県能登地方  37°30.1′N  137°12.6′E  13 km  3.0  震度１
999  2022/11/08  14:14:00.9  トカラ列島近海  29°37.6′N  129°45.7′E   8 km  3.6  震度３

[1000 rows x 8 columns]

In [13]:
# 컬럼 합치기
data1['발생시각'] = data1['발생일'] + data1['발생시각']
data1

,발생일,발생시각,위치,위도,경도,깊이(km),규모,진도
0,2023/05/20,2023/05/2023:11:21.2,千葉県南東沖,34°57.6′N,140°13.1′E,79 km,4.2,震度２
1,2023/05/20,2023/05/2012:21:40.2,トカラ列島近海,29°55.8′N,130°02.6′E,11 km,2.3,震度１
2,2023/05/20,2023/05/2011:27:55.8,トカラ列島近海,29°55.8′N,130°01.1′E,9 km,2.2,震度１
3,2023/05/20,2023/05/2004:13:49.5,三陸沖,39°37.6′N,144°28.4′E,54 km,4.7,震度１
4,2023/05/20,2023/05/2000:57:58.0,与那国島近海,24°21.6′N,122°59.1′E,48 km,3.2,震度１
...,...,...,...,...,...,...,...,...
995,2022/11/09,2022/11/0909:18:47.7,宮城県沖,38°27.3′N,141°53.3′E,55 km,4.0,震度１
996,2022/11/09,2022/11/0905:28:59.1,奄美大島近海,27°58.6′N,129°09.4′E,17 km,3.2,震度１
997,2022/11/09,2022/11/0902:38:10.6,宮古島近海,24°49.2′N,125°22.7′E,49 km,3.9,震度２
998,2022/11/08,2022/11/0817:38:53.7,石川県能登地方,37°30.1′N,137°12.6′E,13 km,3.0,震度１
999,2022/11/08,2022/11/0814:14:00.9,トカラ列島近海,29°37.6′N,129°45.7′E,8 km,3.6,震度３

In [14]:
data1 = data1.drop('발생일', axis=1)
data1

                     발생시각       위치         위도          경도 깊이(km)   규모   진도
0    2023/05/2023:11:21.2   千葉県南東沖  34°57.6′N  140°13.1′E  79 km  4.2  震度２
1    2023/05/2012:21:40.2  トカラ列島近海  29°55.8′N  130°02.6′E  11 km  2.3  震度１
2    2023/05/2011:27:55.8  トカラ列島近海  29°55.8′N  130°01.1′E   9 km  2.2  震度１
3    2023/05/2004:13:49.5      三陸沖  39°37.6′N  144°28.4′E  54 km  4.7  震度１
4    2023/05/2000:57:58.0   与那国島近海  24°21.6′N  122°59.1′E  48 km  3.2  震度１
..                    ...      ...        ...         ...    ...  ...  ...
995  2022/11/0909:18:47.7     宮城県沖  38°27.3′N  141°53.3′E  55 km  4.0  震度１
996  2022/11/0905:28:59.1   奄美大島近海  27°58.6′N  129°09.4′E  17 km  3.2  震度１
997  2022/11/0902:38:10.6    宮古島近海  24°49.2′N  125°22.7′E  49 km  3.9  震度２
998  2022/11/0817:38:53.7  石川県能登地方  37°30.1′N  137°12.6′E  13 km  3.0  震度１
999  2022/11/0814:14:00.9  トカラ列島近海  29°37.6′N  129°45.7′E   8 km  3.6  震度３

[1000 rows x 7 columns]

In [15]:
data2 = pd.read_csv('C:\Pandas\project(mini1)\datasets\地震リスト (2).csv')
data2

         地震の発生日     地震の発生時刻     震央地名         緯度          経度     深さ    Ｍ 最大震度
0    2022/11/06  19:44:26.2    大分県中部  33°17.2′N  131°27.6′E   8 km  1.6  震度１
1    2022/11/06  13:23:32.0   北海道東方沖  43°14.8′N  146°51.9′E  52 km  5.4  震度３
2    2022/11/06  09:06:55.8    長野県南部  35°56.3′N  138°06.1′E   5 km  2.7  震度２
3    2022/11/06  00:32:02.0      日向灘  31°42.6′N  131°47.3′E  33 km  3.8  震度１
4    2022/11/05  14:49:20.6     宮城県沖  37°52.4′N  141°42.4′E  63 km  3.9  震度１
..          ...         ...      ...        ...         ...    ...  ...  ...
209  2022/09/23  11:03:32.8     苫小牧沖  41°58.3′N  141°51.1′E  44 km  2.8  震度１
210  2022/09/23  09:53:51.9    茨城県南部  36°04.5′N  140°12.1′E  83 km  4.7  震度３
211  2022/09/23  07:19:24.2  沖縄本島北西沖  26°21.3′N  125°59.1′E  26 km  4.6  震度１
212  2022/09/23  02:53:36.8    長野県南部  35°54.3′N  137°39.3′E  11 km  2.6  震度１
213  2022/09/23  00:31:33.4  石川県能登地方  37°31.2′N  137°18.4′E  13 km  2.7  震度１

[214 rows x 8 columns]

In [16]:
data2.columns = ['발생일', '발생시각', '위치', '위도', '경도', '깊이(km)', '규모', '진도']
data2

            발생일        발생시각       위치         위도          경도 깊이(km)   규모   진도
0    2022/11/06  19:44:26.2    大分県中部  33°17.2′N  131°27.6′E   8 km  1.6  震度１
1    2022/11/06  13:23:32.0   北海道東方沖  43°14.8′N  146°51.9′E  52 km  5.4  震度３
2    2022/11/06  09:06:55.8    長野県南部  35°56.3′N  138°06.1′E   5 km  2.7  震度２
3    2022/11/06  00:32:02.0      日向灘  31°42.6′N  131°47.3′E  33 km  3.8  震度１
4    2022/11/05  14:49:20.6     宮城県沖  37°52.4′N  141°42.4′E  63 km  3.9  震度１
..          ...         ...      ...        ...         ...    ...  ...  ...
209  2022/09/23  11:03:32.8     苫小牧沖  41°58.3′N  141°51.1′E  44 km  2.8  震度１
210  2022/09/23  09:53:51.9    茨城県南部  36°04.5′N  140°12.1′E  83 km  4.7  震度３
211  2022/09/23  07:19:24.2  沖縄本島北西沖  26°21.3′N  125°59.1′E  26 km  4.6  震度１
212  2022/09/23  02:53:36.8    長野県南部  35°54.3′N  137°39.3′E  11 km  2.6  震度１
213  2022/09/23  00:31:33.4  石川県能登地方  37°31.2′N  137°18.4′E  13 km  2.7  震度１

[214 rows x 8 columns]

In [17]:
data2['발생시각'] = data2['발생일'] + data2['발생시각']
data2

,발생일,발생시각,위치,위도,경도,깊이(km),규모,진도
0,2022/11/06,2022/11/0619:44:26.2,大分県中部,33°17.2′N,131°27.6′E,8 km,1.6,震度１
1,2022/11/06,2022/11/0613:23:32.0,北海道東方沖,43°14.8′N,146°51.9′E,52 km,5.4,震度３
2,2022/11/06,2022/11/0609:06:55.8,長野県南部,35°56.3′N,138°06.1′E,5 km,2.7,震度２
3,2022/11/06,2022/11/0600:32:02.0,日向灘,31°42.6′N,131°47.3′E,33 km,3.8,震度１
4,2022/11/05,2022/11/0514:49:20.6,宮城県沖,37°52.4′N,141°42.4′E,63 km,3.9,震度１
...,...,...,...,...,...,...,...,...
209,2022/09/23,2022/09/2311:03:32.8,苫小牧沖,41°58.3′N,141°51.1′E,44 km,2.8,震度１
210,2022/09/23,2022/09/2309:53:51.9,茨城県南部,36°04.5′N,140°12.1′E,83 km,4.7,震度３
211,2022/09/23,2022/09/2307:19:24.2,沖縄本島北西沖,26°21.3′N,125°59.1′E,26 km,4.6,震度１
212,2022/09/23,2022/09/2302:53:36.8,長野県南部,35°54.3′N,137°39.3′E,11 km,2.6,震度１
213,2022/09/23,2022/09/2300:31:33.4,石川県能登地方,37°31.2′N,137°18.4′E,13 km,2.7,震度１

In [18]:
data2 = data2.drop('발생일', axis=1)
data2

                     발생시각       위치         위도          경도 깊이(km)   규모   진도
0    2022/11/0619:44:26.2    大分県中部  33°17.2′N  131°27.6′E   8 km  1.6  震度１
1    2022/11/0613:23:32.0   北海道東方沖  43°14.8′N  146°51.9′E  52 km  5.4  震度３
2    2022/11/0609:06:55.8    長野県南部  35°56.3′N  138°06.1′E   5 km  2.7  震度２
3    2022/11/0600:32:02.0      日向灘  31°42.6′N  131°47.3′E  33 km  3.8  震度１
4    2022/11/0514:49:20.6     宮城県沖  37°52.4′N  141°42.4′E  63 km  3.9  震度１
..                    ...      ...        ...         ...    ...  ...  ...
209  2022/09/2311:03:32.8     苫小牧沖  41°58.3′N  141°51.1′E  44 km  2.8  震度１
210  2022/09/2309:53:51.9    茨城県南部  36°04.5′N  140°12.1′E  83 km  4.7  震度３
211  2022/09/2307:19:24.2  沖縄本島北西沖  26°21.3′N  125°59.1′E  26 km  4.6  震度１
212  2022/09/2302:53:36.8    長野県南部  35°54.3′N  137°39.3′E  11 km  2.6  震度１
213  2022/09/2300:31:33.4  石川県能登地方  37°31.2′N  137°18.4′E  13 km  2.7  震度１

[214 rows x 7 columns]

In [19]:
data3 = pd.concat([data1, data2], axis=0)
data3

                     발생시각       위치         위도          경도 깊이(km)   규모   진도
0    2023/05/2023:11:21.2   千葉県南東沖  34°57.6′N  140°13.1′E  79 km  4.2  震度２
1    2023/05/2012:21:40.2  トカラ列島近海  29°55.8′N  130°02.6′E  11 km  2.3  震度１
2    2023/05/2011:27:55.8  トカラ列島近海  29°55.8′N  130°01.1′E   9 km  2.2  震度１
3    2023/05/2004:13:49.5      三陸沖  39°37.6′N  144°28.4′E  54 km  4.7  震度１
4    2023/05/2000:57:58.0   与那国島近海  24°21.6′N  122°59.1′E  48 km  3.2  震度１
..                    ...      ...        ...         ...    ...  ...  ...
209  2022/09/2311:03:32.8     苫小牧沖  41°58.3′N  141°51.1′E  44 km  2.8  震度１
210  2022/09/2309:53:51.9    茨城県南部  36°04.5′N  140°12.1′E  83 km  4.7  震度３
211  2022/09/2307:19:24.2  沖縄本島北西沖  26°21.3′N  125°59.1′E  26 km  4.6  震度１
212  2022/09/2302:53:36.8    長野県南部  35°54.3′N  137°39.3′E  11 km  2.6  震度１
213  2022/09/2300:31:33.4  石川県能登地方  37°31.2′N  137°18.4′E  13 km  2.7  震度１

[1214 rows x 7 columns]

In [20]:
data4 = pd.concat([data, data3], axis=0)
data4

,번호,발생시각,규모,깊이(km),진도,위도,경도,위치,지도보기,상세정보
1,101,2023/09/22 17:46:58,2.2,14,Ⅱ,36.59 N,128.22 E,경북 문경시 동쪽 3km 지역,지도,상세정보
2,100,2023/09/16 04:28:25,2.2,7,Ⅱ,36.01 N,128.01 E,경북 김천시 남남서쪽 17km 지역,지도,상세정보
3,99,2023/09/14 21:28:25,2.9,23,Ⅰ,35.70 N,130.03 E,울산 동구 동북동쪽 60km 해역,지도,상세정보
4,98,2023/09/08 05:12:01,2.3,19,Ⅰ,41.32 N,129.17 E,북한 함경북도 길주 북북서쪽 43km 지역,지도,상세정보
5,97,2023/09/08 04:01:16,2.1,24,Ⅰ,41.30 N,129.23 E,북한 함경북도 길주 북북서쪽 39km 지역,지도,상세정보
...,...,...,...,...,...,...,...,...,...,...
209,NaN,2022/09/2311:03:32.8,2.8,44 km,震度１,41°58.3′N,141°51.1′E,苫小牧沖,NaN,NaN
210,NaN,2022/09/2309:53:51.9,4.7,83 km,震度３,36°04.5′N,140°12.1′E,茨城県南部,NaN,NaN
211,NaN,2022/09/2307:19:24.2,4.6,26 km,震度１,26°21.3′N,125°59.1′E,沖縄本島北西沖,NaN,NaN
212,NaN,2022/09/2302:53:36.8,2.6,11 km,震度１,35°54.3′N,137°39.3′E,長野県南部,NaN,NaN
213,NaN,2022/09/2300:31:33.4,2.7,13 km,震度１,37°31.2′N,137°18.4′E,石川県能登地方,NaN,NaN

In [21]:
data4.info

<bound method DataFrame.info of       번호                  발생시각   규모 깊이(km)   진도         위도          경도  \
1    101   2023/09/22 17:46:58  2.2     14    Ⅱ    36.59 N    128.22 E
2    100   2023/09/16 04:28:25  2.2      7    Ⅱ    36.01 N    128.01 E
3     99   2023/09/14 21:28:25  2.9     23    Ⅰ    35.70 N    130.03 E
4     98   2023/09/08 05:12:01  2.3     19    Ⅰ    41.32 N    129.17 E
5     97   2023/09/08 04:01:16  2.1     24    Ⅰ    41.30 N    129.23 E
..   ...                   ...  ...    ...  ...        ...         ...
209  NaN  2022/09/2311:03:32.8  2.8  44 km  震度１  41°58.3′N  141°51.1′E
210  NaN  2022/09/2309:53:51.9  4.7  83 km  震度３  36°04.5′N  140°12.1′E
211  NaN  2022/09/2307:19:24.2  4.6  26 km  震度１  26°21.3′N  125°59.1′E
212  NaN  2022/09/2302:53:36.8  2.6  11 km  震度１  35°54.3′N  137°39.3′E
213  NaN  2022/09/2300:31:33.4  2.7  13 km  震度１  37°31.2′N  137°18.4′E

                          위치 지도보기  상세정보
1           경북 문경시 동쪽 3km 지역   지도  상세정보
2        경북 김천시 남남서쪽 17km 지역   지도  상세정보
3         울산 동구 동북동쪽 60km 해역   지도  상세정보
4    북한 함경북도 길주 북북서쪽 43km 지역   지도  상세정보
5    북한 함경북도 길주 북북서쪽 39km 지역   지도  상세정보
..                       ...  ...   ...
209                     苫小牧沖  NaN   NaN
210                    茨城県南部  NaN   NaN
211                  沖縄本島北西沖  NaN   NaN
212                    長野県南部  NaN   NaN
213                  石川県能登地方  NaN   NaN

[1315 rows x 10 columns]>

In [30]:
data12 = pd.read_csv('datasets/korea_.csv')
data12

            ot   MT  dep  sc      lat       lon                     spot
0   2023-09-22  2.2   14   2  36.59 N  128.22 E         경북 문경시 동쪽 3km 지역
1   2023-09-16  2.2    7   2  36.01 N  128.01 E      경북 김천시 남남서쪽 17km 지역
2   2023-09-14  2.9   23   1  35.70 N  130.03 E       울산 동구 동북동쪽 60km 해역
3   2023-09-08  2.3   19   1  41.32 N  129.17 E  북한 함경북도 길주 북북서쪽 43km 지역
4   2023-09-08  2.1   24   1  41.30 N  129.23 E  북한 함경북도 길주 북북서쪽 39km 지역
..         ...  ...  ...  ..      ...       ...                      ...
84  2022-10-08  2.4   14   1  41.29 N  129.21 E  북한 함경북도 길주 북북서쪽 39km 지역
85  2022-10-08  2.5   23   1  41.30 N  129.13 E  북한 함경북도 길주 북북서쪽 42km 지역
86  2022-10-01  2.7   14   3  36.94 N  127.13 E   충남 천안시 서북구 북북서쪽 7km 지역
87  2022-09-22  2.9   10   1  40.57 N  126.71 E    북한 자강도 용림 북북동쪽 7km 지역
88  2022-09-11  2.4   13   1  36.46 N  129.63 E      경북 영덕군 동북동쪽 24km 해역

[89 rows x 7 columns]

In [31]:
def clean_location(data12):
    # "°"와 "N"을 빈 문자열로 대체하여 제거
    cleaned_location = data12.replace(" N", "")
    return cleaned_location
# 'Location' 컬럼에 apply() 함수 적용
data12['lat'] = data12['lat'].apply(clean_location)

In [32]:
def clean_location(data12):
    # "°"와 "N"을 빈 문자열로 대체하여 제거
    cleaned_location = data12.replace(" E", "")
    return cleaned_location
# 'Location' 컬럼에 apply() 함수 적용
data12['lon'] = data12['lon'].apply(clean_location)

In [33]:
data12

            ot   MT  dep  sc    lat     lon                     spot
0   2023-09-22  2.2   14   2  36.59  128.22         경북 문경시 동쪽 3km 지역
1   2023-09-16  2.2    7   2  36.01  128.01      경북 김천시 남남서쪽 17km 지역
2   2023-09-14  2.9   23   1  35.70  130.03       울산 동구 동북동쪽 60km 해역
3   2023-09-08  2.3   19   1  41.32  129.17  북한 함경북도 길주 북북서쪽 43km 지역
4   2023-09-08  2.1   24   1  41.30  129.23  북한 함경북도 길주 북북서쪽 39km 지역
..         ...  ...  ...  ..    ...     ...                      ...
84  2022-10-08  2.4   14   1  41.29  129.21  북한 함경북도 길주 북북서쪽 39km 지역
85  2022-10-08  2.5   23   1  41.30  129.13  북한 함경북도 길주 북북서쪽 42km 지역
86  2022-10-01  2.7   14   3  36.94  127.13   충남 천안시 서북구 북북서쪽 7km 지역
87  2022-09-22  2.9   10   1  40.57  126.71    북한 자강도 용림 북북동쪽 7km 지역
88  2022-09-11  2.4   13   1  36.46  129.63      경북 영덕군 동북동쪽 24km 해역

[89 rows x 7 columns]

In [34]:
excel_file_path = 'korea_1.xlsx'
data12.to_excel(excel_file_path, index=False)

In [49]:
data15 = data12.rename(columns = {'ot' : 'OT', 'dep' : 'DEP', 'sc' : 'SC', 'lat' : 'LAT', 'lon' : 'LON', 'spot' : 'SPOT'})

In [50]:
data15

            OT   MT  DEP  SC    LAT     LON                     SPOT
0   2023-09-22  2.2   14   2  36.59  128.22         경북 문경시 동쪽 3km 지역
1   2023-09-16  2.2    7   2  36.01  128.01      경북 김천시 남남서쪽 17km 지역
2   2023-09-14  2.9   23   1  35.70  130.03       울산 동구 동북동쪽 60km 해역
3   2023-09-08  2.3   19   1  41.32  129.17  북한 함경북도 길주 북북서쪽 43km 지역
4   2023-09-08  2.1   24   1  41.30  129.23  북한 함경북도 길주 북북서쪽 39km 지역
..         ...  ...  ...  ..    ...     ...                      ...
84  2022-10-08  2.4   14   1  41.29  129.21  북한 함경북도 길주 북북서쪽 39km 지역
85  2022-10-08  2.5   23   1  41.30  129.13  북한 함경북도 길주 북북서쪽 42km 지역
86  2022-10-01  2.7   14   3  36.94  127.13   충남 천안시 서북구 북북서쪽 7km 지역
87  2022-09-22  2.9   10   1  40.57  126.71    북한 자강도 용림 북북동쪽 7km 지역
88  2022-09-11  2.4   13   1  36.46  129.63      경북 영덕군 동북동쪽 24km 해역

[89 rows x 7 columns]

In [141]:
excel_file_path = 'korea_1.xlsx'
data12.to_excel(excel_file_path, index=False)

In [28]:
data12

NameError: name 'data12' is not defined

In [90]:
data12.dtypes

ot       object
MT      float64
dep       int64
sc        int64
lat      object
lon      object
spot     object
dtype: object

In [110]:
data12 = data12.astype({'lon' : 'float'})
data12.dtypes

ot      datetime64[ns]
MT             float64
dep            float64
sc             float64
lat            float64
lon            float64
spot            object
dtype: object

In [102]:
data12['ot'] = pd.to_datetime(data12['ot'])

In [112]:
# 위도 28~42, 경도 121~140

In [18]:
data13 = pd.read_excel('datasets/Japan_2023earthquake.xlsx')
data13

            OT     SPOT    LAT     LON  DEP   MT  SC
0   2023-05-20   千葉県南東沖  34.57  140.13   79  4.2   2
1   2023-05-20  トカラ列島近海  29.55  130.02   11  2.3   1
2   2023-05-20  トカラ列島近海  29.55  130.01    9  2.2   1
3   2023-05-20   与那国島近海  24.21  122.59   48  3.2   1
4   2023-05-19  トカラ列島近海  29.56  130.01   10  2.1   1
..         ...      ...    ...     ...  ...  ...  ..
881 2022-09-24   兵庫県南東部  34.47  135.19    9  4.0   3
882 2022-09-23    茨城県南部  36.04  140.12   83  4.7   3
883 2022-09-23  沖縄本島北西沖  26.21  125.59   26  4.6   1
884 2022-09-23    長野県南部  35.54  137.39   11  2.6   1
885 2022-09-23  石川県能登地方  37.31  137.18   13  2.7   1

[886 rows x 7 columns]

In [19]:
new_column_order = ['OT', 'MT', 'DEP', 'SC', 'LAT', 'LON', 'SPOT']
data14 = data13[new_column_order]
data14

            OT   MT  DEP  SC    LAT     LON     SPOT
0   2023-05-20  4.2   79   2  34.57  140.13   千葉県南東沖
1   2023-05-20  2.3   11   1  29.55  130.02  トカラ列島近海
2   2023-05-20  2.2    9   1  29.55  130.01  トカラ列島近海
3   2023-05-20  3.2   48   1  24.21  122.59   与那国島近海
4   2023-05-19  2.1   10   1  29.56  130.01  トカラ列島近海
..         ...  ...  ...  ..    ...     ...      ...
881 2022-09-24  4.0    9   3  34.47  135.19   兵庫県南東部
882 2022-09-23  4.7   83   3  36.04  140.12    茨城県南部
883 2022-09-23  4.6   26   1  26.21  125.59  沖縄本島北西沖
884 2022-09-23  2.6   11   1  35.54  137.39    長野県南部
885 2022-09-23  2.7   13   1  37.31  137.18  石川県能登地方

[886 rows x 7 columns]

In [20]:
data14['OT'] = pd.to_datetime(data14['OT'], 'YYYY-mm-dd')
data14

            OT   MT  DEP  SC    LAT     LON     SPOT
0   2023-05-20  4.2   79   2  34.57  140.13   千葉県南東沖
1   2023-05-20  2.3   11   1  29.55  130.02  トカラ列島近海
2   2023-05-20  2.2    9   1  29.55  130.01  トカラ列島近海
3   2023-05-20  3.2   48   1  24.21  122.59   与那国島近海
4   2023-05-19  2.1   10   1  29.56  130.01  トカラ列島近海
..         ...  ...  ...  ..    ...     ...      ...
881 2022-09-24  4.0    9   3  34.47  135.19   兵庫県南東部
882 2022-09-23  4.7   83   3  36.04  140.12    茨城県南部
883 2022-09-23  4.6   26   1  26.21  125.59  沖縄本島北西沖
884 2022-09-23  2.6   11   1  35.54  137.39    長野県南部
885 2022-09-23  2.7   13   1  37.31  137.18  石川県能登地方

[886 rows x 7 columns]

In [161]:
data20 = pd.concat([data15, data14], ignore_index=True)
data20

                      OT   MT  DEP  SC    LAT     LON                     SPOT
0             2023-09-22  2.2   14   2  36.59  128.22         경북 문경시 동쪽 3km 지역
1             2023-09-16  2.2    7   2  36.01  128.01      경북 김천시 남남서쪽 17km 지역
2             2023-09-14  2.9   23   1  35.70  130.03       울산 동구 동북동쪽 60km 해역
3             2023-09-08  2.3   19   1  41.32  129.17  북한 함경북도 길주 북북서쪽 43km 지역
4             2023-09-08  2.1   24   1  41.30  129.23  북한 함경북도 길주 북북서쪽 39km 지역
..                   ...  ...  ...  ..    ...     ...                      ...
970  2022-09-24 00:00:00  4.0    9   3  34.47  135.19                   兵庫県南東部
971  2022-09-23 00:00:00  4.7   83   3  36.04  140.12                    茨城県南部
972  2022-09-23 00:00:00  4.6   26   1  26.21  125.59                  沖縄本島北西沖
973  2022-09-23 00:00:00  2.6   11   1  35.54  137.39                    長野県南部
974  2022-09-23 00:00:00  2.7   13   1  37.31  137.18                  石川県能登地方

[975 rows x 7 columns]

In [163]:
data20['OT'] = pd.to_datetime(data20['OT']).dt.strftime('%Y-%m-%d')
data20

             OT   MT  DEP  SC    LAT     LON                     SPOT
0    2023-09-22  2.2   14   2  36.59  128.22         경북 문경시 동쪽 3km 지역
1    2023-09-16  2.2    7   2  36.01  128.01      경북 김천시 남남서쪽 17km 지역
2    2023-09-14  2.9   23   1  35.70  130.03       울산 동구 동북동쪽 60km 해역
3    2023-09-08  2.3   19   1  41.32  129.17  북한 함경북도 길주 북북서쪽 43km 지역
4    2023-09-08  2.1   24   1  41.30  129.23  북한 함경북도 길주 북북서쪽 39km 지역
..          ...  ...  ...  ..    ...     ...                      ...
970  2022-09-24  4.0    9   3  34.47  135.19                   兵庫県南東部
971  2022-09-23  4.7   83   3  36.04  140.12                    茨城県南部
972  2022-09-23  4.6   26   1  26.21  125.59                  沖縄本島北西沖
973  2022-09-23  2.6   11   1  35.54  137.39                    長野県南部
974  2022-09-23  2.7   13   1  37.31  137.18                  石川県能登地方

[975 rows x 7 columns]

In [184]:
--------------------------------------------------------------------------------------------------

SyntaxError: invalid syntax (2307179982.py, line 1)

In [164]:
excel_file_path = 'korea_Japan.xlsx'
data20.to_excel(excel_file_path, index=False)

In [7]:
excel_file_path = '국내지진목록_.xlsx'
data_df.to_excel(excel_file_path, index=False)

In [179]:
data21 = data20[['MT', 'DEP', 'SC', 'LAT','LON']]

In [180]:
data21

      MT  DEP  SC    LAT     LON
0    2.2   14   2  36.59  128.22
1    2.2    7   2  36.01  128.01
2    2.9   23   1  35.70  130.03
3    2.3   19   1  41.32  129.17
4    2.1   24   1  41.30  129.23
..   ...  ...  ..    ...     ...
970  4.0    9   3  34.47  135.19
971  4.7   83   3  36.04  140.12
972  4.6   26   1  26.21  125.59
973  2.6   11   1  35.54  137.39
974  2.7   13   1  37.31  137.18

[975 rows x 5 columns]

In [181]:
# 
y_target = data21['MT']
X_data = data21.drop(['MT'], axis=1,inplace=False)

In [182]:
plt.scatter(MT, )
plt.xlabel('length')
plt.ylabel('weight')
plt.show()

     DEP  SC    LAT     LON
0     14   2  36.59  128.22
1      7   2  36.01  128.01
2     23   1  35.70  130.03
3     19   1  41.32  129.17
4     24   1  41.30  129.23
..   ...  ..    ...     ...
970    9   3  34.47  135.19
971   83   3  36.04  140.12
972   26   1  26.21  125.59
973   11   1  35.54  137.39
974   13   1  37.31  137.18

[975 rows x 4 columns]

In [23]:
data30 = pd.read_csv('datasets/국내지진목록 5년차.csv')
data30

                    OT   MT DEP SC      LAT       LON                     SPOT
0      2023-09-27 0:48  3.2   6  Ⅰ  41.33 N  129.16 E  북한 함경북도 길주 북북서쪽 44km 지역
1     2023-09-26 21:35  1.4   7  Ⅰ  35.36 N  126.30 E      전남 영광군 서북서쪽 21km 해역
2      2023-09-26 9:46  1.2  12  Ⅰ  36.44 N  128.05 E      경북 상주시 서북서쪽 10km 지역
3      2023-09-26 0:20  1.5   9  Ⅰ  39.03 N  126.57 E  북한 평안남도 양덕 남남서쪽 21km 지역
4     2023-09-25 23:01  1.2   9  Ⅰ  34.98 N  127.38 E      전남 순천시 서북서쪽 10km 지역
...                ...  ...  .. ..      ...       ...                      ...
3318  2019-09-01 12:58  2.3  16  Ⅰ  39.51 N  126.10 E   북한 평안남도 개천 남동쪽 27km 지역
3319   2019-09-01 8:04  1.0   6  Ⅰ  37.96 N  124.64 E   인천 옹진군 백령도 서북서쪽 4km 지역
3320   2019-09-01 7:43  1.1  10  Ⅰ  36.37 N  127.23 E       충남 공주시 남동쪽 13km 지역
3321   2019-09-01 6:53  1.0   9  Ⅰ  37.97 N  124.59 E   인천 옹진군 백령도 서북서쪽 8km 해역
3322   2019-09-01 2:34  1.0  12  Ⅰ  36.08 N  128.64 E      경북 군위군 남남동쪽 19km 지역

[3323 rows x 7 columns]

In [24]:
data30['OT'] = pd.to_datetime(data30['OT'], 'YYYY-mm-dd')
data30

AssertionError:

In [26]:
def clean_location(data30):
    # "°"와 "N"을 빈 문자열로 대체하여 제거
    cleaned_location = data30.replace(" N", "")
    return cleaned_location
# 'Location' 컬럼에 apply() 함수 적용
data30['LAT'] = data30['LAT'].apply(clean_location)

In [27]:
def clean_location(data30):
    # "°"와 "N"을 빈 문자열로 대체하여 제거
    cleaned_location = data30.replace(" N", "")
    return cleaned_location
# 'Location' 컬럼에 apply() 함수 적용
data30['LON'] = data30['LON'].apply(clean_location)