In [1]:
import pandas as pd

data = pd.read_csv('datasets/국내지진목록 5년차.csv')
data

,N,OT,MT,DEP,SC,LAT,LON,SPOT
0,1,2023-09-27 0:48,3.2,6,Ⅰ,41.33 N,129.16 E,북한 함경북도 길주 북북서쪽 44km 지역
1,2,2023-09-26 21:35,1.4,7,Ⅰ,35.36 N,126.30 E,전남 영광군 서북서쪽 21km 해역
2,3,2023-09-26 9:46,1.2,12,Ⅰ,36.44 N,128.05 E,경북 상주시 서북서쪽 10km 지역
3,4,2023-09-26 0:20,1.5,9,Ⅰ,39.03 N,126.57 E,북한 평안남도 양덕 남남서쪽 21km 지역
4,5,2023-09-25 23:01,1.2,9,Ⅰ,34.98 N,127.38 E,전남 순천시 서북서쪽 10km 지역
...,...,...,...,...,...,...,...,...
3318,3319,2019-09-01 12:58,2.3,16,Ⅰ,39.51 N,126.10 E,북한 평안남도 개천 남동쪽 27km 지역
3319,3320,2019-09-01 8:04,1.0,6,Ⅰ,37.96 N,124.64 E,인천 옹진군 백령도 서북서쪽 4km 지역
3320,3321,2019-09-01 7:43,1.1,10,Ⅰ,36.37 N,127.23 E,충남 공주시 남동쪽 13km 지역
3321,3322,2019-09-01 6:53,1.0,9,Ⅰ,37.97 N,124.59 E,인천 옹진군 백령도 서북서쪽 8km 해역
3322,3323,2019-09-01 2:34,1.0,12,Ⅰ,36.08 N,128.64 E,경북 군위군 남남동쪽 19km 지역

In [70]:
data['OT'] = pd.to_datetime(data['OT']).dt.strftime('%Y-%m-%d')
data

         N          OT   MT DEP SC      LAT       LON                     SPOT
0        1  2023-09-27  3.2   6  Ⅰ  41.33 N  129.16 E  북한 함경북도 길주 북북서쪽 44km 지역
1        2  2023-09-26  1.4   7  Ⅰ  35.36 N  126.30 E      전남 영광군 서북서쪽 21km 해역
2        3  2023-09-26  1.2  12  Ⅰ  36.44 N  128.05 E      경북 상주시 서북서쪽 10km 지역
3        4  2023-09-26  1.5   9  Ⅰ  39.03 N  126.57 E  북한 평안남도 양덕 남남서쪽 21km 지역
4        5  2023-09-25  1.2   9  Ⅰ  34.98 N  127.38 E      전남 순천시 서북서쪽 10km 지역
...    ...         ...  ...  .. ..      ...       ...                      ...
3318  3319  2019-09-01  2.3  16  Ⅰ  39.51 N  126.10 E   북한 평안남도 개천 남동쪽 27km 지역
3319  3320  2019-09-01  1.0   6  Ⅰ  37.96 N  124.64 E   인천 옹진군 백령도 서북서쪽 4km 지역
3320  3321  2019-09-01  1.1  10  Ⅰ  36.37 N  127.23 E       충남 공주시 남동쪽 13km 지역
3321  3322  2019-09-01  1.0   9  Ⅰ  37.97 N  124.59 E   인천 옹진군 백령도 서북서쪽 8km 해역
3322  3323  2019-09-01  1.0  12  Ⅰ  36.08 N  128.64 E      경북 군위군 남남동쪽 19km 지역

[3323 rows x 8 columns]

In [2]:
def clean_location(data):
    # "°"와 "N"을 빈 문자열로 대체하여 제거
    cleaned_location = data.replace(" N", "")
    return cleaned_location
# 'Location' 컬럼에 apply() 함수 적용
data['LAT'] = data['LAT'].apply(clean_location)

def clean_location(data):
    # "°"와 "N"을 빈 문자열로 대체하여 제거
    cleaned_location = data.replace(" E", "")
    return cleaned_location
# 'Location' 컬럼에 apply() 함수 적용
data['LON'] = data['LON'].apply(clean_location)

In [3]:
data

,N,OT,MT,DEP,SC,LAT,LON,SPOT
0,1,2023-09-27 0:48,3.2,6,Ⅰ,41.33,129.16,북한 함경북도 길주 북북서쪽 44km 지역
1,2,2023-09-26 21:35,1.4,7,Ⅰ,35.36,126.30,전남 영광군 서북서쪽 21km 해역
2,3,2023-09-26 9:46,1.2,12,Ⅰ,36.44,128.05,경북 상주시 서북서쪽 10km 지역
3,4,2023-09-26 0:20,1.5,9,Ⅰ,39.03,126.57,북한 평안남도 양덕 남남서쪽 21km 지역
4,5,2023-09-25 23:01,1.2,9,Ⅰ,34.98,127.38,전남 순천시 서북서쪽 10km 지역
...,...,...,...,...,...,...,...,...
3318,3319,2019-09-01 12:58,2.3,16,Ⅰ,39.51,126.10,북한 평안남도 개천 남동쪽 27km 지역
3319,3320,2019-09-01 8:04,1.0,6,Ⅰ,37.96,124.64,인천 옹진군 백령도 서북서쪽 4km 지역
3320,3321,2019-09-01 7:43,1.1,10,Ⅰ,36.37,127.23,충남 공주시 남동쪽 13km 지역
3321,3322,2019-09-01 6:53,1.0,9,Ⅰ,37.97,124.59,인천 옹진군 백령도 서북서쪽 8km 해역
3322,3323,2019-09-01 2:34,1.0,12,Ⅰ,36.08,128.64,경북 군위군 남남동쪽 19km 지역

In [4]:
data['SC'] = data['SC'].astype(str)

In [5]:
# 로마숫자를 아라비아 숫자로
def hihi(a):
    if a == "Ⅰ":
        return 1
    elif a == "Ⅱ":
        return 2
    elif a == "Ⅲ":
        return 3
    elif a == "Ⅳ":
        return 4
    else:
        return 5
data['SC'] = data['SC'].apply(hihi)

In [6]:
data

,N,OT,MT,DEP,SC,LAT,LON,SPOT
0,1,2023-09-27 0:48,3.2,6,1,41.33,129.16,북한 함경북도 길주 북북서쪽 44km 지역
1,2,2023-09-26 21:35,1.4,7,1,35.36,126.30,전남 영광군 서북서쪽 21km 해역
2,3,2023-09-26 9:46,1.2,12,1,36.44,128.05,경북 상주시 서북서쪽 10km 지역
3,4,2023-09-26 0:20,1.5,9,1,39.03,126.57,북한 평안남도 양덕 남남서쪽 21km 지역
4,5,2023-09-25 23:01,1.2,9,1,34.98,127.38,전남 순천시 서북서쪽 10km 지역
...,...,...,...,...,...,...,...,...
3318,3319,2019-09-01 12:58,2.3,16,1,39.51,126.10,북한 평안남도 개천 남동쪽 27km 지역
3319,3320,2019-09-01 8:04,1.0,6,1,37.96,124.64,인천 옹진군 백령도 서북서쪽 4km 지역
3320,3321,2019-09-01 7:43,1.1,10,1,36.37,127.23,충남 공주시 남동쪽 13km 지역
3321,3322,2019-09-01 6:53,1.0,9,1,37.97,124.59,인천 옹진군 백령도 서북서쪽 8km 해역
3322,3323,2019-09-01 2:34,1.0,12,1,36.08,128.64,경북 군위군 남남동쪽 19km 지역

In [7]:
excel_file_path = 'korea(5년치).xlsx'
data.to_excel(excel_file_path, index=False)